services:
  getcryptoprice:
    build: .
    container_name: getCryptoPrice
    restart: always
    # network_mode: bridge
    networks:
      - gcp_network
    volumes:
      - .:/app
    # env_file:
    #   - .env
    ports:
      - "8088:8080"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - gcp_network

volumes:
  db_data:

networks:
  gcp_network:
    driver: bridge